# Configuración del Back-end (Conexión directa a tu repositorio público)
backend:
  name: github 
  # Nombre exacto de tu repositorio:
  repo: 'EstebanCamposArts/EstudiantsApp' 
  branch: main 
  auth_scope: 'repo'

# Configuración de Medios (imágenes)
media_folder: "assets/images" 
public_folder: "/assets/images"

# -----------------
# Estructura del Contenido Editable (Tus archivos HTML)
# El widget 'code' permite editar el HTML completo de la página.
# -----------------
collections:
  - name: "pages"
    label: "Páginas del Sitio"
    files:
      - file: "altrescosetes.html"
        label: "Altresolucetes"
        name: "altrescosetes"
        fields:
          - {label: "Contenido de la Página", name: "body", widget: "code"}
      
      - file: "elbrillofestero.html"
        label: "El Brillo Festero"
        name: "elbrillofestero"
        fields:
          - {label: "Contenido de la Página", name: "body", widget: "code"}

      - file: "escuadres.html"
        label: "Escuadras y Grupos"
        name: "escuadres"
        fields:
          - {label: "Contenido de la Página", name: "body", widget: "code"}
          
      - file: "festes2026.html"
        label: "Fiestas 2026"
        name: "festes2026"
        fields:
          - {label: "Contenido de la Página", name: "body", widget: "code"}
          
      - file: "index.html"
        label: "Página de Inicio (Home)"
        name: "index"
        fields:
          - {label: "Contenido de la Página", name: "body", widget: "code"}

      - file: "lacomparsa.html"
        label: "La Comparsa"
        name: "lacomparsa"
        fields:
          - {label: "Contenido de la Página", name: "body", widget: "code"}

      - file: "lesbandesdemusica.html"
        label: "Bandas de Música"
        name: "lesbandesdemusica"
        fields:
          - {label: "Contenido de la Página", name: "body", widget: "code"}
          
      - file: "themigha.html"
        label: "The Migha"
        name: "themigha"
        fields:
          - {label: "Contenido de la Página", name: "body", widget: "code"}