# Configuración del Back-end (Conexión a GitHub)
backend:
  name: github 
  # Nombre del repositorio en GitHub: TU_USUARIO/NOMBRE_DEL_REPOSITORIO
  repo: 'tu_usuario/nombre_del_repositorio' 
  branch: main # La rama principal donde quieres que se guarden los cambios
  # Usa 'proxy_url' si estás en desarrollo local con Netlify
  # proxy_url: http://localhost:8081/api/v1/github

# Habilitar la autenticación de GitHub (se recomienda usar Netlify Identity)
auth_scope: 'repo'

# -----------------
# Estructura del Contenido a Editar
# -----------------

collections:
  - name: "pages"
    label: "Páginas Estáticas Principales"
    files:
      # Configuración de 'altrescosetes.html'
      - file: "altrescosetes.html"
        label: "Altresolucetes"
        name: "altrescosetes"
        fields:
          # Puedes usar un widget 'code' para que editen el HTML completo
          - {label: "Código HTML Completo", name: "body", widget: "code", default: "<h1>Contenido por defecto...</h1>"}

      # Configuración de 'festes2026.html'
      - file: "festes2026.html"
        label: "Fiestas 2026"
        name: "festes2026"
        fields:
          # O puedes hacer editable solo una parte específica (ej. entre <h1> y </h1>)
          - {label: "Título de la Fiesta", name: "title", widget: "string", default: "Fiestas 2026"}
          - {label: "Detalles del Evento (Markdown)", name: "details", widget: "markdown"}
          - {label: "Fecha", name: "date", widget: "datetime"}

      # Configuración de 'index.html'
      - file: "index.html"
        label: "Página Principal"
        name: "index"
        fields:
          - {label: "Contenido de la Portada", name: "content", widget: "markdown"}

      # Añade el resto de tus archivos aquí siguiendo el mismo patrón...